# Generated by Django 5.0.6 on 2024-10-05 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('image_name', models.CharField(max_length=110, verbose_name='تصویر اصلی مقاله')),
                ('short_text', models.TextField(verbose_name='متن خلاصه مقاله')),
                ('text', models.TextField(verbose_name='متن مقاله')),
                ('key_words', models.CharField(max_length=200, verbose_name='کلمات کلیدی')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ درج مقاله')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار مقاله')),
                ('update_date', models.DateField(auto_now=True, verbose_name='تاریخ اخرین ویرایش مقاله')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('pdf_file_name', models.CharField(max_length=200, verbose_name='فایل pdf مقاله')),
                ('view_number', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('slug', models.SlugField(max_length=250)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'db_table': 't_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, verbose_name='عنوان گروه مقالات')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
                'db_table': 't_artcle_groups',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=50, verbose_name='نام حانوادرگی')),
                ('education', models.CharField(max_length=50, verbose_name='تحطیلات')),
                ('job', models.CharField(max_length=50, verbose_name='شغل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
                'db_table': 't_author',
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200, verbose_name='نام تصویر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'db_table': 't_article_gallery',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.articlegroup', verbose_name='گروه مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='blogApp.author', verbose_name='نویسنده مقاله'),
        ),
    ]
