# Generated by Django 5.0.6 on 2024-08-19 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('title_message', models.CharField(max_length=60, verbose_name='موضوع پیام')),
                ('text_message', models.TextField(verbose_name='متن پیام')),
                ('Time_message', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت پیام')),
                ('show_message', models.BooleanField(default=False, verbose_name='دیده شده/دیده نشده')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_title', models.CharField(max_length=50, verbose_name='عنوان مکان')),
                ('Origina_photo', models.ImageField(upload_to='images/garden', verbose_name='عکس اصلی')),
                ('Time_Visit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ساعت بازدید')),
                ('Description', models.TextField(verbose_name='اطلاعات بیشتر')),
                ('Rules', models.CharField(max_length=200, verbose_name='قوانین')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_title', models.CharField(max_length=50, verbose_name='عنوان گروه')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_price', models.IntegerField(verbose_name=' بهای بلیط')),
                ('place_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduction.place', verbose_name='مکان بازدید')),
                ('group_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduction.visitor_group', verbose_name='گروه بازدید')),
            ],
        ),
    ]
