# Generated by Django 5.0.6 on 2024-08-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0002_alter_message_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor_group',
            options={'verbose_name': 'بازدید کننده', 'verbose_name_plural': 'بازدید کننده ها'},
        ),
        migrations.AlterModelTable(
            name='visitor_group',
            table='t_Visitor_Group',
        ),
    ]
